package configfile

import (
	"fmt"
	"sort"
	"strings"
)

// GitconfigWriter implements the Writer interface for git config format.
// Generates INI-style config with sections, subsections, and multi-value support.
//
// Expected structure:
//
//	core:
//	  editor: nvim
//	user:
//	  name: "Your Name"
//	  email: "you@example.com"
//	alias:
//	  s: status
//	  co: checkout
//	credential:
//	  "https://github.com":
//	    helper:
//	      - ""
//	      - "!/opt/homebrew/bin/gh auth git-credential"
//	includeIf:
//	  "gitdir:~/Repos/work/":
//	    path: "~/.config/git/config.work"
type GitconfigWriter struct{}

func init() {
	Register(&GitconfigWriter{})
}

// Format returns the format identifier.
func (w *GitconfigWriter) Format() string {
	return "gitconfig"
}

// Write generates git config content from values.
func (w *GitconfigWriter) Write(values map[string]interface{}) ([]byte, error) {
	var b strings.Builder

	b.WriteString("# Git Configuration\n")
	b.WriteString("# Generated by acorn - do not edit manually\n\n")

	// Define section order for readable output
	sectionOrder := []string{
		"core", "user", "init", "color", "alias",
		"push", "pull", "fetch", "merge", "rebase", "diff",
		"credential", "include", "includeIf",
	}

	// Write known sections first in order
	written := make(map[string]bool)
	for _, section := range sectionOrder {
		if val, ok := values[section]; ok {
			if err := w.writeSection(&b, section, val); err != nil {
				return nil, err
			}
			written[section] = true
		}
	}

	// Write any remaining sections alphabetically
	remaining := make([]string, 0)
	for section := range values {
		if !written[section] {
			remaining = append(remaining, section)
		}
	}
	sort.Strings(remaining)
	for _, section := range remaining {
		if err := w.writeSection(&b, section, values[section]); err != nil {
			return nil, err
		}
	}

	return []byte(b.String()), nil
}

// writeSection writes a section with its values.
func (w *GitconfigWriter) writeSection(b *strings.Builder, name string, value interface{}) error {
	switch v := value.(type) {
	case map[string]interface{}:
		// Check if this is a subsection container (like credential or includeIf)
		if w.hasSubsections(v) {
			return w.writeSubsections(b, name, v)
		}
		// Regular section with key-value pairs
		b.WriteString(fmt.Sprintf("[%s]\n", name))
		w.writeKeyValues(b, v)
		b.WriteString("\n")

	case []interface{}:
		// Special handling for include (list of paths)
		if name == "include" && len(v) > 0 {
			b.WriteString("[include]\n")
			for _, path := range v {
				b.WriteString(fmt.Sprintf("\tpath = %s\n", path))
			}
			b.WriteString("\n")
		}
	}

	return nil
}

// hasSubsections checks if a map contains nested maps (subsections).
func (w *GitconfigWriter) hasSubsections(m map[string]interface{}) bool {
	for _, v := range m {
		if _, ok := v.(map[string]interface{}); ok {
			return true
		}
	}
	return false
}

// writeSubsections writes sections with subsection names like [credential "url"].
func (w *GitconfigWriter) writeSubsections(b *strings.Builder, section string, subsections map[string]interface{}) error {
	// Sort subsection names for deterministic output
	names := make([]string, 0, len(subsections))
	for name := range subsections {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		val := subsections[name]
		if m, ok := val.(map[string]interface{}); ok {
			b.WriteString(fmt.Sprintf("[%s %q]\n", section, name))
			w.writeKeyValues(b, m)
			b.WriteString("\n")
		}
	}

	return nil
}

// writeKeyValues writes key-value pairs with proper indentation.
func (w *GitconfigWriter) writeKeyValues(b *strings.Builder, m map[string]interface{}) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		val := m[key]
		// Handle multi-value keys (arrays)
		if arr, ok := toGitconfigSlice(val); ok {
			for _, item := range arr {
				b.WriteString(fmt.Sprintf("\t%s = %s\n", key, item))
			}
		} else {
			b.WriteString(fmt.Sprintf("\t%s = %s\n", key, formatGitconfigValue(val)))
		}
	}
}

// toGitconfigSlice converts an interface to a string slice if it's an array type.
func toGitconfigSlice(v interface{}) ([]string, bool) {
	switch val := v.(type) {
	case []string:
		return val, true
	case []interface{}:
		result := make([]string, 0, len(val))
		for _, item := range val {
			result = append(result, fmt.Sprintf("%v", item))
		}
		return result, true
	default:
		return nil, false
	}
}

// formatGitconfigValue formats a value for git config output.
func formatGitconfigValue(v interface{}) string {
	switch val := v.(type) {
	case string:
		return val
	case bool:
		if val {
			return "true"
		}
		return "false"
	case int, int64, float64:
		return fmt.Sprintf("%v", val)
	default:
		return fmt.Sprintf("%v", val)
	}
}
