// Package componentconfig provides typed configuration for acorn shell components.
package componentconfig

// BaseConfig is the common structure for all component configurations.
// Each component's config.yaml should follow this schema.
type BaseConfig struct {
	// Metadata
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Version     string `yaml:"version,omitempty"`

	// Environment variables to export (key-value)
	Env map[string]string `yaml:"env,omitempty"`

	// Paths to add to PATH
	Paths []PathEntry `yaml:"paths,omitempty"`

	// Shell aliases (name -> command)
	Aliases map[string]string `yaml:"aliases,omitempty"`

	// Wrapper functions that call acorn commands
	Wrappers []Wrapper `yaml:"wrappers,omitempty"`

	// Raw shell functions (for interactive code that can't be generated)
	ShellFunctions map[string]string `yaml:"shell_functions,omitempty"`

	// Config files to generate for this component
	Files []FileConfig `yaml:"files,omitempty"`

	// SyncFiles defines files to sync from dotfiles repo to user locations
	SyncFiles []SyncFileConfig `yaml:"sync_files,omitempty"`

	// Installation configuration for this component
	Install InstallConfig `yaml:"install,omitempty"`
}

// FileConfig defines a config file to be generated by acorn.
type FileConfig struct {
	// Target is the output path (supports env vars like ${XDG_CONFIG_HOME})
	Target string `yaml:"target"`

	// Format is the output format identifier (ghostty, json, yaml, toml, ini, keyvalue)
	Format string `yaml:"format"`

	// Platforms is an optional list of platforms this file applies to (darwin, linux)
	// If empty, the file is generated on all platforms
	Platforms []string `yaml:"platforms,omitempty"`

	// Schema defines the field types and defaults (optional, for validation)
	Schema map[string]FieldSchema `yaml:"schema,omitempty"`

	// Values are the actual values to write to the file
	Values map[string]interface{} `yaml:"values"`
}

// SyncFileConfig defines a file to sync from the dotfiles repo to a user location.
type SyncFileConfig struct {
	// Source is the path relative to $DOTFILES_ROOT (e.g., "ai/claude/settings.json")
	Source string `yaml:"source"`

	// Target is the destination path (supports env vars like ${HOME}/.claude/settings.json)
	Target string `yaml:"target"`

	// Mode defines how to handle the file: "copy", "symlink", or "merge"
	// - copy: Copy the file (user can modify freely)
	// - symlink: Create a symlink to the dotfiles version
	// - merge: Merge dotfiles version with user's local version (JSON only)
	Mode string `yaml:"mode"`

	// MergeConfig defines merge behavior (only used when Mode is "merge")
	MergeConfig *MergeConfig `yaml:"merge,omitempty"`
}

// MergeConfig defines how to merge config files.
type MergeConfig struct {
	// Strategy defines merge strategy: "deep" (recursive merge) or "shallow" (top-level only)
	Strategy string `yaml:"strategy"`

	// UserFile is the path to user's local additions (merged on top of source)
	// If empty, uses Target + ".local" suffix
	UserFile string `yaml:"user_file,omitempty"`

	// PreserveUserKeys lists keys that should always be preserved from user file
	PreserveUserKeys []string `yaml:"preserve_user_keys,omitempty"`
}

// FieldSchema defines the schema for a config field.
type FieldSchema struct {
	// Type is the field type: string, int, bool, float, list, map
	Type string `yaml:"type"`

	// Default is the default value if not specified in Values
	Default interface{} `yaml:"default,omitempty"`

	// Items is the item type for list fields
	Items string `yaml:"items,omitempty"`

	// Description is optional documentation for the field
	Description string `yaml:"description,omitempty"`
}

// PathEntry represents a path to add to PATH with optional conditions.
type PathEntry struct {
	// Path is the path to add (supports shell variable expansion)
	Path string `yaml:"path"`

	// Condition is an optional platform filter: "darwin", "linux", or empty for all
	Condition string `yaml:"condition,omitempty"`
}

// Wrapper defines an acorn command wrapper function.
type Wrapper struct {
	// Name is the shell function name
	Name string `yaml:"name"`

	// Command is the acorn command to call (e.g., "acorn go new")
	Command string `yaml:"command"`

	// Usage is the usage hint shown when called without args (optional)
	Usage string `yaml:"usage,omitempty"`

	// DefaultArg is a default argument if none provided (optional)
	DefaultArg string `yaml:"default_arg,omitempty"`

	// PostAction is a special action after command: "cd" to change directory
	PostAction string `yaml:"post_action,omitempty"`

	// RequiresArg if true, shows usage and returns 1 if no arg provided
	RequiresArg bool `yaml:"requires_arg,omitempty"`
}

// InstallConfig defines installation configuration for a component.
type InstallConfig struct {
	// Tools is the list of tools to install for this component
	Tools []ToolInstall `yaml:"tools,omitempty"`
}

// ToolInstall defines how to install a single tool.
type ToolInstall struct {
	// Name is the tool/binary name
	Name string `yaml:"name"`

	// Description is a human-readable description (optional)
	Description string `yaml:"description,omitempty"`

	// Check is the command to verify installation (e.g., "command -v wrangler")
	Check string `yaml:"check"`

	// Methods defines platform-specific installation methods
	// Keys: darwin, linux, windows, or distro-specific like linux/debian
	Methods map[string]InstallMethod `yaml:"methods"`

	// Requires lists prerequisites (command names or component:command format)
	Requires []string `yaml:"requires,omitempty"`

	// PostInstall defines actions after installation
	PostInstall PostInstallConfig `yaml:"post_install,omitempty"`
}

// InstallMethod defines a platform-specific installation method.
type InstallMethod struct {
	// Type is the installation type: brew, apt, npm, pip, cargo, go, curl, binary
	Type string `yaml:"type"`

	// Package is the package name (if different from tool name)
	Package string `yaml:"package,omitempty"`

	// Global indicates global installation (for npm, pip)
	Global bool `yaml:"global,omitempty"`

	// URL is the download URL (for curl, binary types)
	URL string `yaml:"url,omitempty"`

	// Args are additional arguments for the install command
	Args []string `yaml:"args,omitempty"`
}

// PostInstallConfig defines post-installation actions.
type PostInstallConfig struct {
	// Message is displayed to the user after installation
	Message string `yaml:"message,omitempty"`

	// Commands are executed after installation (optional)
	Commands []string `yaml:"commands,omitempty"`
}

// HasInstall returns true if the component has installation configuration.
func (c *BaseConfig) HasInstall() bool {
	return len(c.Install.Tools) > 0
}

// HasSyncFiles returns true if the component has sync file configuration.
func (c *BaseConfig) HasSyncFiles() bool {
	return len(c.SyncFiles) > 0
}

// GetSyncFiles returns sync files configuration, never nil.
func (c *BaseConfig) GetSyncFiles() []SyncFileConfig {
	if c.SyncFiles == nil {
		return []SyncFileConfig{}
	}
	return c.SyncFiles
}

// GetEnv returns environment variables as a map, never nil.
func (c *BaseConfig) GetEnv() map[string]string {
	if c.Env == nil {
		return make(map[string]string)
	}
	return c.Env
}

// GetAliases returns aliases as a map, never nil.
func (c *BaseConfig) GetAliases() map[string]string {
	if c.Aliases == nil {
		return make(map[string]string)
	}
	return c.Aliases
}

// GetShellFunctions returns shell functions as a map, never nil.
func (c *BaseConfig) GetShellFunctions() map[string]string {
	if c.ShellFunctions == nil {
		return make(map[string]string)
	}
	return c.ShellFunctions
}
