package neomutt

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mistergrinvalds/acorn/internal/utils/configfile"
)

// Writer implements the configfile.Writer interface for NeoMutt muttrc format.
// Supports:
//   - set key = value
//   - bind context key action
//   - color element foreground background
//   - macro context key action "description"
type Writer struct{}

func init() {
	configfile.Register(&Writer{})
}

// NewWriter creates a new NeoMutt config writer.
func NewWriter() *Writer {
	return &Writer{}
}

// Format returns the format identifier.
func (w *Writer) Format() string {
	return "muttrc"
}

// Write generates NeoMutt muttrc content from values.
// Expected structure:
//
//	settings:
//	  editor: vim
//	  sort: reverse-date
//	bindings:
//	  - context: index,pager
//	    key: \Ck
//	    action: sidebar-prev
//	colors:
//	  - element: sidebar_new
//	    foreground: yellow
//	    background: default
//	macros:
//	  - context: index,pager
//	    key: <f2>
//	    action: '<sync-mailbox><enter-command>source ...<enter>'
//	    description: Switch account
func (w *Writer) Write(values map[string]any) ([]byte, error) {
	var b strings.Builder

	b.WriteString("# NeoMutt Configuration\n")
	b.WriteString("# Generated by acorn - edit with care\n\n")

	// Write settings (set key = value)
	if settings, ok := values["settings"].(map[string]any); ok {
		b.WriteString("# ===== Settings =====\n")
		keys := sortedKeys(settings)
		for _, key := range keys {
			value := settings[key]
			b.WriteString(fmt.Sprintf("set %s = %s\n", key, formatMuttValue(value)))
		}
		b.WriteString("\n")
	}

	// Write bindings (bind context key action)
	if bindings, ok := values["bindings"].([]any); ok && len(bindings) > 0 {
		b.WriteString("# ===== Keybindings =====\n")
		for _, binding := range bindings {
			if bind, ok := binding.(map[string]any); ok {
				context := getString(bind, "context")
				key := getString(bind, "key")
				action := getString(bind, "action")
				if context != "" && key != "" && action != "" {
					b.WriteString(fmt.Sprintf("bind %s %s %s\n", context, key, action))
				}
			}
		}
		b.WriteString("\n")
	}

	// Write colors (color element foreground background)
	if colors, ok := values["colors"].([]any); ok && len(colors) > 0 {
		b.WriteString("# ===== Colors =====\n")
		for _, color := range colors {
			if c, ok := color.(map[string]any); ok {
				element := getString(c, "element")
				fg := getString(c, "foreground")
				bg := getString(c, "background")
				if element != "" && fg != "" && bg != "" {
					b.WriteString(fmt.Sprintf("color %s %s %s\n", element, fg, bg))
				}
			}
		}
		b.WriteString("\n")
	}

	// Write macros (macro context key action "description")
	if macros, ok := values["macros"].([]any); ok && len(macros) > 0 {
		b.WriteString("# ===== Macros =====\n")
		for _, macro := range macros {
			if m, ok := macro.(map[string]any); ok {
				context := getString(m, "context")
				key := getString(m, "key")
				action := getString(m, "action")
				desc := getString(m, "description")
				if context != "" && key != "" && action != "" {
					if desc != "" {
						b.WriteString(fmt.Sprintf("macro %s %s '%s' \"%s\"\n", context, key, action, desc))
					} else {
						b.WriteString(fmt.Sprintf("macro %s %s '%s'\n", context, key, action))
					}
				}
			}
		}
		b.WriteString("\n")
	}

	// Write source commands (source path)
	if sources, ok := values["sources"].([]any); ok && len(sources) > 0 {
		b.WriteString("# ===== Account Sources =====\n")
		for _, source := range sources {
			if s, ok := source.(string); ok {
				b.WriteString(fmt.Sprintf("source %s\n", s))
			}
		}
		b.WriteString("\n")
	}

	// Write folder hooks
	if hooks, ok := values["folder_hooks"].([]any); ok && len(hooks) > 0 {
		b.WriteString("# ===== Folder Hooks =====\n")
		for _, hook := range hooks {
			if h, ok := hook.(map[string]any); ok {
				pattern := getString(h, "pattern")
				command := getString(h, "command")
				if pattern != "" && command != "" {
					b.WriteString(fmt.Sprintf("folder-hook '%s' '%s'\n", pattern, command))
				}
			}
		}
		b.WriteString("\n")
	}

	// Write raw content at the end
	if raw, ok := values["raw"].(string); ok && raw != "" {
		b.WriteString("# ===== Additional Configuration =====\n")
		b.WriteString(raw)
		b.WriteString("\n")
	}

	return []byte(b.String()), nil
}

// sortedKeys returns sorted keys from a map.
func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// getString safely gets a string value from a map.
func getString(m map[string]any, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

// formatMuttValue formats a value for muttrc.
func formatMuttValue(v any) string {
	switch val := v.(type) {
	case string:
		// Quote strings with spaces or special chars
		if strings.ContainsAny(val, " \t\"'") {
			return fmt.Sprintf("%q", val)
		}
		return val
	case bool:
		if val {
			return "yes"
		}
		return "no"
	case int, int64, float64:
		return fmt.Sprintf("%v", val)
	default:
		return fmt.Sprintf("%v", val)
	}
}

// AccountWriter generates account-specific muttrc files.
type AccountWriter struct{}

// NewAccountWriter creates a new account writer.
func NewAccountWriter() *AccountWriter {
	return &AccountWriter{}
}

// WriteGmailAccount generates a Gmail account config.
func (w *AccountWriter) WriteGmailAccount(email, realName, tokenFile string) []byte {
	var b strings.Builder

	b.WriteString("# Gmail Account\n")
	b.WriteString(fmt.Sprintf("set from = %q\n", email))
	b.WriteString(fmt.Sprintf("set realname = %q\n", realName))
	b.WriteString("\n")

	b.WriteString("# IMAP with OAuth2\n")
	b.WriteString(fmt.Sprintf("set imap_user = %q\n", email))
	b.WriteString("set imap_authenticators = \"oauthbearer:xoauth2\"\n")
	b.WriteString(fmt.Sprintf("set imap_oauth_refresh_command = \"python3 ~/.config/neomutt/mutt_oauth2.py %s\"\n", tokenFile))
	b.WriteString("set folder = \"imaps://imap.gmail.com:993\"\n")
	b.WriteString("set spoolfile = \"+INBOX\"\n")
	b.WriteString("set postponed = \"+[Gmail]/Drafts\"\n")
	b.WriteString("set trash = \"+[Gmail]/Trash\"\n")
	b.WriteString("set record = \"+[Gmail]/Sent Mail\"\n")
	b.WriteString("\n")

	b.WriteString("# SMTP with OAuth2\n")
	b.WriteString(fmt.Sprintf("set smtp_url = \"smtps://%s@smtp.gmail.com:465\"\n", email))
	b.WriteString("set smtp_authenticators = \"oauthbearer:xoauth2\"\n")
	b.WriteString(fmt.Sprintf("set smtp_oauth_refresh_command = \"python3 ~/.config/neomutt/mutt_oauth2.py %s\"\n", tokenFile))
	b.WriteString("\n")

	b.WriteString("# Mailboxes\n")
	b.WriteString("unmailboxes *\n")
	b.WriteString("mailboxes =INBOX =[Gmail]/Sent\\ Mail =[Gmail]/Drafts =[Gmail]/Spam =[Gmail]/Trash\n")
	b.WriteString("\n")

	b.WriteString("# Signature\n")
	username := strings.Split(email, "@")[0]
	b.WriteString(fmt.Sprintf("set signature = \"~/.config/neomutt/signatures/gmail-%s\"\n", username))
	b.WriteString("\n")

	b.WriteString("# Account color\n")
	b.WriteString("color status green default\n")

	return []byte(b.String())
}

// WriteMicrosoftAccount generates a Microsoft/Office365 account config.
func (w *AccountWriter) WriteMicrosoftAccount(email, realName, tokenFile string) []byte {
	var b strings.Builder

	b.WriteString("# Microsoft/Office365 Account\n")
	b.WriteString(fmt.Sprintf("set from = %q\n", email))
	b.WriteString(fmt.Sprintf("set realname = %q\n", realName))
	b.WriteString("\n")

	b.WriteString("# IMAP with OAuth2\n")
	b.WriteString(fmt.Sprintf("set imap_user = %q\n", email))
	b.WriteString("set imap_authenticators = \"oauthbearer:xoauth2\"\n")
	b.WriteString(fmt.Sprintf("set imap_oauth_refresh_command = \"python3 ~/.config/neomutt/mutt_oauth2.py %s\"\n", tokenFile))
	b.WriteString("set folder = \"imaps://outlook.office365.com:993\"\n")
	b.WriteString("set spoolfile = \"+INBOX\"\n")
	b.WriteString("set postponed = \"+Drafts\"\n")
	b.WriteString("set trash = \"+Trash\"\n")
	b.WriteString("set record = \"+Sent\"\n")
	b.WriteString("\n")

	b.WriteString("# SMTP with OAuth2\n")
	b.WriteString(fmt.Sprintf("set smtp_url = \"smtps://%s@smtp.office365.com:587\"\n", email))
	b.WriteString("set smtp_authenticators = \"oauthbearer:xoauth2\"\n")
	b.WriteString(fmt.Sprintf("set smtp_oauth_refresh_command = \"python3 ~/.config/neomutt/mutt_oauth2.py %s\"\n", tokenFile))
	b.WriteString("\n")

	b.WriteString("# Mailboxes\n")
	b.WriteString("unmailboxes *\n")
	b.WriteString("mailboxes =INBOX =Sent =Drafts =Spam =Trash\n")
	b.WriteString("\n")

	b.WriteString("# Signature\n")
	b.WriteString(fmt.Sprintf("set signature = \"~/.config/neomutt/signatures/microsoft-%s\"\n", strings.ReplaceAll(email, "@", "-")))
	b.WriteString("\n")

	b.WriteString("# Account color\n")
	b.WriteString("color status blue default\n")

	return []byte(b.String())
}
